name: Deploy Promotions

on:
  push:
    branches:
      - main
    paths:
      - 'promotions/**/*.json'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Deploy Promotion
        env:
          TRYONYOU_API_KEY: ${{ secrets.TRYONYOU_API_KEY }}
        run: |
          bash ./scripts/automate_promotions.sh
